# Generated by Django 3.1 on 2020-09-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0002_auto_20200903_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='expiration_at',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='expiration_in',
            new_name='expires_in',
        ),
    ]
