# Generated by Django 3.1 on 2020-09-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('REST_API', '0003_auto_20200904_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
